using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace LArseneCraftingCatalogue.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Armors",
                columns: table => new
                {
                    ArmorId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    MaterialCost = table.Column<string>(type: "TEXT", nullable: true),
                    ToolId = table.Column<int>(type: "INTEGER", nullable: false),
                    DC = table.Column<string>(type: "TEXT", nullable: true),
                    TimeToCraft = table.Column<int>(type: "INTEGER", nullable: false),
                    ItemValue = table.Column<string>(type: "TEXT", nullable: true),
                    Weight = table.Column<string>(type: "TEXT", nullable: true),
                    ArmorType = table.Column<string>(type: "TEXT", nullable: true),
                    ArmorClass = table.Column<string>(type: "TEXT", nullable: true),
                    StrengthRequirement = table.Column<string>(type: "TEXT", nullable: true),
                    StealthModifier = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Armors", x => x.ArmorId);
                });

            migrationBuilder.CreateTable(
                name: "Essence",
                columns: table => new
                {
                    EssenceId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    CreatureCR = table.Column<string>(type: "TEXT", nullable: true),
                    DC = table.Column<string>(type: "TEXT", nullable: true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    ItemRarity = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Essence", x => x.EssenceId);
                });

            migrationBuilder.CreateTable(
                name: "MagicItems",
                columns: table => new
                {
                    MagicItemId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    MagicItemType = table.Column<string>(type: "TEXT", nullable: true),
                    ItemValue = table.Column<string>(type: "TEXT", nullable: true),
                    Rarity = table.Column<string>(type: "TEXT", nullable: true),
                    Attunement = table.Column<string>(type: "TEXT", nullable: true),
                    MetaTag = table.Column<string>(type: "TEXT", nullable: true),
                    MonsterComponentId = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MagicItems", x => x.MagicItemId);
                });

            migrationBuilder.CreateTable(
                name: "MonsterComponents",
                columns: table => new
                {
                    MonsterComponentId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    Type = table.Column<string>(type: "TEXT", nullable: true),
                    DC = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MonsterComponents", x => x.MonsterComponentId);
                });

            migrationBuilder.CreateTable(
                name: "Tools",
                columns: table => new
                {
                    ToolId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    AbilityRequirement = table.Column<string>(type: "TEXT", nullable: true),
                    ItemTypes = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Tools", x => x.ToolId);
                });

            migrationBuilder.CreateTable(
                name: "Weapons",
                columns: table => new
                {
                    WeaponId = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Name = table.Column<string>(type: "TEXT", nullable: true),
                    MaterialCost = table.Column<string>(type: "TEXT", nullable: true),
                    ToolId = table.Column<int>(type: "INTEGER", nullable: false),
                    DC = table.Column<string>(type: "TEXT", nullable: true),
                    TimeToCraft = table.Column<double>(type: "REAL", nullable: false),
                    ItemValue = table.Column<string>(type: "TEXT", nullable: true),
                    Weight = table.Column<string>(type: "TEXT", nullable: true),
                    WeaponType = table.Column<string>(type: "TEXT", nullable: true),
                    Damage = table.Column<string>(type: "TEXT", nullable: true),
                    Properties = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Weapons", x => x.WeaponId);
                });

            migrationBuilder.InsertData(
                table: "Armors",
                columns: new[] { "ArmorId", "ArmorClass", "ArmorType", "DC", "ItemValue", "MaterialCost", "Name", "StealthModifier", "StrengthRequirement", "TimeToCraft", "ToolId", "Weight" },
                values: new object[,]
                {
                    { 1, "11 + Dex mod", "Light", "13", "5gp", "2gp", "Padded", "Disadvantage", "None", 8, 1, "8lb" },
                    { 2, "11 + Dex mod", "Light", "15", "10gp", "3gp", "Leather", "None", "None", 16, 1, "10lb" },
                    { 3, "12 + Dex mod", "Light", "17", "45gp", "15gp", "Studded Leather", "Disadvantage", "None", 24, 1, "13lb" },
                    { 4, "12 + Dex mod (max 2)", "Medium", "13", "10gp", "3gp", "Hide", "None", "None", 8, 1, "12lb" },
                    { 5, "13 + Dex mod (max 2)", "Medium", "15", "50gp", "17gp", "Chain shirt", "None", "None", 16, 16, "20lb" },
                    { 6, "14 + Dex mod (max 2)", "Medium", "17", "50gp", "17gp", "Scale mail", "Disadvantage", "None", 24, 16, "45lb" },
                    { 7, "14 + Dex mod (max 2)", "Medium", "18", "400gp", "130gp", "Breastplate", "None", "None", 40, 16, "20lb" },
                    { 8, "15 + Dex mod (max 2)", "Medium", "19", "750gp", "250gp", "Half plate", "Disadvantage", "None", 80, 16, "40lb" },
                    { 9, "14", "Heavy", "15", "30gp", "10gp", "Ring mail", "Disadvantage", "None", 16, 16, "40lb" },
                    { 10, "16", "Heavy", "16", "75gp", "25gp", "Chain mail", "Disadvantage", "Str 13", 32, 16, "55lb" },
                    { 11, "17", "Heavy", "18", "200gp", "70gp", "Splint", "Disadvantage", "Str 15", 40, 16, "60lb" },
                    { 12, "18", "Heavy", "20", "1500gp", "500gp", "Plate", "Disadvantage", "Str 15", 200, 16, "65lb" },
                    { 13, "+2", "Shield", "13", "10gp", "3gp", "Shield", "None", "None", 8, 16, "6lb" }
                });

            migrationBuilder.InsertData(
                table: "Essence",
                columns: new[] { "EssenceId", "CreatureCR", "DC", "ItemRarity", "Name" },
                values: new object[,]
                {
                    { 1, "3-6", "25", "Uncommon", "Frail essence" },
                    { 2, "7-11", "30", "Rare", "Robust essence" },
                    { 3, "12-17", "35", "Very Rare", "Potent essence" },
                    { 4, "18-24", "40", "Legendary", "Mythic essence" },
                    { 5, "25+", "50", "Artifact", "Deific essence" }
                });

            migrationBuilder.InsertData(
                table: "MagicItems",
                columns: new[] { "MagicItemId", "Attunement", "ItemValue", "MagicItemType", "MetaTag", "MonsterComponentId", "Name", "Rarity" },
                values: new object[,]
                {
                    { 1, null, "25gp", "ammunition", null, 0, "+1 Ammunition", "U" },
                    { 2, null, "100gp", "ammunition", null, 0, "+2 Ammunition", "R" },
                    { 3, null, "480gp", "ammunition", null, 0, "+3 Ammunition", "V" },
                    { 4, null, "550gp", "ammunition", null, 0, "Arrow of Slaying", "V" },
                    { 5, "Req", "1,200gp", "Armor", "Tavern mimic", 0, "Breastplank", "U" },
                    { 6, "none", "1500gp", "armor", "Dinosaur", 0, "+1 Armor", "R" },
                    { 7, "none", "6500gp", "armor", "Gorgon", 0, "+2 Armor", "V" },
                    { 8, "none", "28,800gp", "armor", "Magnetite", 0, "+3 Armor", "L" },
                    { 9, "none", "500gp", "armor", "", 0, "Adamantine Armor", "U" },
                    { 10, "Required", "1200gp", "armor", "Black pudding", 0, "Armor of Acid Resistance", "U" },
                    { 11, "Required", "1200gp", "armor", "Ice devil", 0, "Armor of Cold Resistance", "U" },
                    { 12, "Required", "1500gp", "armor", "Salamander", 0, "Armor of Fire Resistance", "U" },
                    { 13, "Required", "1200gp", "armor", "Golem", 0, "Armor of Force Resistance", "U" },
                    { 14, "Required", "1200gp", "armor", "Djinni", 0, "Armor of Lightning Resistance", "U" },
                    { 15, "Required", "1200gp", "armor", "Mummy", 0, "Armor of Necrotic Resistance", "U" },
                    { 16, "Required", "1500gp", "armor", "Naga", 0, "Armor of Poison Resistance", "U" },
                    { 17, "Required", "1100gp", "armor", "Aboleth", 0, "Armor of Psychic Resistance", "U" },
                    { 18, "Required", "1100gp", "armor", "Planetar", 0, "Armor of Radiant Resistance", "U" },
                    { 19, "Required", "1100gp", "armor", "Storm", 0, "Armor of Thunder Resistance", "U" },
                    { 20, "none", "400gp", "armor", "", 0, "Mithral Armor", "U" },
                    { 21, "Req", "18000gp", "armour (heavy)", "Golem", 0, "Armor of Invulnerability", "L" },
                    { 22, "Req", "3000gp", "armour (heavy)", "Demon", 0, "Demon Armor", "R" },
                    { 23, "", "6500gp", "armour (heavy)", "", 0, "Dwarven Plate", "V" },
                    { 24, "", "2100gp", "armour (light)", "Hag", 0, "Glamoured Studded Leather", "R" },
                    { 25, "Req", "9400gp", "armour (medium)", "Black", 0, "Black Dragon Scale Mail", "V" },
                    { 26, "Req", "9400gp", "armour (medium)", "Blue", 0, "Blue Dragon Scale Mail", "V" },
                    { 27, "Req", "9400gp", "armour (medium)", "Brass", 0, "Brass Dragon Scale Mail", "V" },
                    { 28, "Req", "9400gp", "armour (medium)", "Bronze", 0, "Bronze Dragon Scale Mail", "V" },
                    { 29, "Req", "9400gp", "armour (medium)", "Copper", 0, "Copper Dragon Scale Mail", "v" },
                    { 30, "Req", "9400gp", "armour (medium)", "Gold", 0, "Gold Dragon Scale Mail", "V" },
                    { 31, "Req", "9400gp", "armour (medium)", "Green", 0, "Green Dragon Scale Mail", "v" },
                    { 32, "Req", "9400gp", "armour (medium)", "Red", 0, "Red Dragon Scale Mail", "V" },
                    { 33, "Req", "9400gp", "armour (medium)", "Silver", 0, "Silver Dragon Scale Mail", "v" },
                    { 34, "Req", "9400gp", "armour (medium)", "White", 0, "White Dragon Scale Mail", "v" },
                    { 35, "", "2500gp", "armour (medium)", "", 0, "Elven Chain", "R" },
                    { 36, "Req", "1200gp", "armour (medium or heavy)", "Magnetite", 0, "Haemscale", "U" },
                    { 37, "Req", "4000gp", "armour (medium or heavy)", "Magnetite", 0, "Haemscale", "R" },
                    { 38, "Req", "52000gp", "armour (medium or heavy)", "Magnetite", 0, "Haemscale", "L" },
                    { 39, "Req", "500gp", "armour (plate)", "", 0, "Armor of Vulnerability", "U" },
                    { 40, "Req", "41600gp", "armour (plate)", "", 0, "Plate Armor of Etherealness", "L" },
                    { 41, "Req", "5000gp", "armour (shield)", "Animated", 0, "Animated Shield", "R" },
                    { 42, "Req", "5000gp", "armour (shield)", "", 0, "Arrow-Catching Shield", "R" },
                    { 43, "", "2300gp", "armour (shield)", "Mechakobold", 0, "Dragonmaw Shield", "R" },
                    { 44, "Req", "650gp", "armour (shield)", "Treant", 0, "Overgrown Barkshield", "U" },
                    { 45, "Req", "2400gp", "armour (shield)", "Treant", 0, "Overgrown Barkshield", "R" },
                    { 46, "Req", "10000gp", "armour (shield)", "Treant", 0, "Overgrown Barkshield", "v" },
                    { 47, "Req", "5000gp", "armour (shield)", "Magnetite", 0, "Shield of Missile Attraction", "R" },
                    { 48, "Req", "25000gp", "armour (shield)", "Shield guardian", 0, "Spellguard Shield", "V" },
                    { 49, "", "1500gp", "armour (shield)", "Beetle", 0, "+1 Shield", "R" },
                    { 50, "", "6500gp", "armour (shield)", "Bulette", 0, "+2 Shield", "V" },
                    { 51, "", "28800gp", "armour (shield)", "", 0, "+3 Shield", "L" },
                    { 52, "", "1900gp", "potion", "", 0, "Oil of Etherealness", "R" },
                    { 53, "", "4800gp", "potion", "", 0, "Oil of Sharpness", "V" },
                    { 54, "", "480gp", "potion", "", 0, "Oil of Slipperiness", "U" },
                    { 55, "", "180gp", "potion", "", 0, "Philter of Love", "U" },
                    { 56, "", "200gp", "potion", "", 0, "Potion of Animal Friendship", "U" },
                    { 57, "", "900gp", "potion", "", 0, "Potion of Clairvoyance", "R" },
                    { 58, "", "50gp", "potion", "Spider", 0, "Potion of Climbing", "C" },
                    { 59, "", "6000gp", "potion", "Cloud", 0, "Potion of Cloud Giant Strength", "V" },
                    { 60, "", "270gp", "potion", "Gnome", 0, "Potion of Diminution", "U" },
                    { 61, "", "3000gp", "potion", "Fire", 0, "Potion of Fire Giant Strength", "R" },
                    { 62, "", "900gp", "potion", "", 0, "Potion of Flying", "R" },
                    { 63, "", "1500gp", "potion", "Frost", 0, "Potion of Frost Giant Strength", "R" },
                    { 64, "", "900gp", "potion", "", 0, "Potion of Gaseous Form", "R" },
                    { 65, "", "250gp", "potion", "", 0, "Potion of Greater Healing", "U" },
                    { 66, "", "270gp", "potion", "", 0, "Potion of Growth", "U" },
                    { 67, "", "50gp", "potion", "", 0, "Potion of Healing", "C" },
                    { 68, "", "180gp", "potion", "", 0, "Potion of Heroism", "U" },
                    { 69, "", "500gp", "potion", "Hill", 0, "Potion of Hill Giant Strength", "U" },
                    { 70, "", "900gp", "potion", "Duergar", 0, "Potion of Invisibility", "R" },
                    { 71, "", "180gp", "potion", "Aboleth", 0, "Potion of Mind Reading", "U" },
                    { 72, "", "180gp", "potion", "", 0, "Potion of Poison", "U" },
                    { 73, "", "240gp", "potion", "", 0, "Potion of Resistance Acid", "U" },
                    { 74, "", "240gp", "potion", "Ice devil", 0, "Potion of Resistance Cold", "U" },
                    { 75, "", "300gp", "potion", "Hell hound", 0, "Potion of Resistance Fire", "U" },
                    { 76, "", "240gp", "potion", "", 0, "Potion of Resistance Force", "U" },
                    { 77, "", "240gp", "potion", "Flesh golem", 0, "Potion of Resistance Lightning", "U" },
                    { 78, "", "240gp", "potion", "", 0, "Potion of Resistance Necrotic", "U" },
                    { 79, "", "300gp", "potion", "Bearded devil", 0, "Potion of Resistance Poison", "U" },
                    { 80, "", "220gp", "potion", "Dreamholder", 0, "Potion of Resistance Psychic", "U" },
                    { 81, "", "220gp", "potion", "Couatl", 0, "Potion of Resistance Radiant", "U" },
                    { 82, "", "220gp", "potion", "Storm", 0, "Potion of Resistance Thunder", "U" },
                    { 83, "", "4800gp", "potion", "", 0, "Potion of Speed", "V" },
                    { 84, "", "1500gp", "potion", "Stone", 0, "Potion of Stone Giant Strength", "R" },
                    { 85, "", "30000gp", "potion", "Storm", 0, "Potion of Storm Giant Strength", "L" },
                    { 86, "", "1000gp", "potion", "", 0, "Potion of Superior Healing", "R" },
                    { 87, "", "5000gp", "potion", "", 0, "Potion of Supreme Healing", "V" },
                    { 88, "", "180gp", "potion", "", 0, "Potion of Water Breathing", "U" },
                    { 89, "Req", "650gp", "ring", "Pygmy rakshasa", 0, "Eye of the Tiger", "U" },
                    { 90, "Req", "9500gp", "ring", "Pygmy rakshasa", 0, "Eye of the Tiger", "V" },
                    { 91, "Req", "35000gp", "ring", "Air elemental", 0, "Ring of Air Elemental Command", "L" },
                    { 92, "", "1500gp", "ring", "", 0, "Ring of Animal Influence", "R" },
                    { 93, "Opt", "550gp", "ring", "Awakened Tree", 0, "Ring of Birdseye Maple", "U" },
                    { 94, "Req", "90000gp", "ring", "Djinni", 0, "Ring of Djinni Summoning", "L" },
                    { 95, "Req", "35000gp", "ring", "Earth elemental", 0, "Ring of Earth Elemental Command", "L" },
                    { 96, "Req", "5000gp", "ring", "", 0, "Ring of Evasion", "R" },
                    { 97, "Req", "2100gp", "ring", "", 0, "Ring of Feather Falling", "R" },
                    { 98, "Req", "35000gp", "ring", "Fire elemental", 0, "Ring of Fire Elemental Command", "L" },
                    { 99, "Req", "16000gp", "ring", "", 0, "Ring of Free Action", "V" },
                    { 100, "Opt", "500gp", "ring", "Fungal heart", 0, "Ring of Fungal Symbiosis", "U" },
                    { 101, "Opt", "9400gp", "ring", "Fungal heart", 0, "Ring of Fungal Symbiosis", "V" },
                    { 102, "Req", "32000gp", "ring", "Invisible stalker", 0, "Ring of Invisibility", "L" },
                    { 103, "Req", "1000gp", "ring", "Frog or toad", 0, "Ring ofJumping", "U" },
                    { 104, "Req", "1600gp", "ring", "", 0, "Ring of Mind Shielding", "U" },
                    { 105, "Req", "1500gp", "ring", "Green", 0, "Ring of Poison Resistance", "UR" },
                    { 106, "Req", "3500gp", "ring", "", 0, "Ring of Protection", "R" },
                    { 107, "Req", "12000gp", "ring", "", 0, "Ring of Regeneration", "V" },
                    { 108, "Req", "1200gp", "ring", "", 0, "Ring of Resistance Acid", "U" },
                    { 109, "Req", "4000gp", "ring", "", 0, "Ring of Resistance Cold", "U" },
                    { 110, "Req", "1500gp", "ring", "", 0, "Ring of Resistance Fire", "U" },
                    { 111, "Req", "1200gp", "ring", "", 0, "Ring of Resistance Force", "U" },
                    { 112, "Req", "1200gp", "ring", "", 0, "Ring of Resistance Lightning", "U" },
                    { 113, "Req", "1200gp", "ring", "", 0, "Ring of Resistance Necrotic", "U" },
                    { 114, "Req", "1500gp", "ring", "", 0, "Ring of Resistance Poison", "U" },
                    { 115, "Req", "1100gp", "ring", "", 0, "Ring of Resistance Psychic", "U" },
                    { 116, "Req", "1100gp", "ring", "", 0, "Ring of Resistance Radiant", "U" },
                    { 117, "Req", "1100gp", "ring", "", 0, "Ring of Resistance Thunder", "U" },
                    { 118, "Req", "14000gp", "ring", "", 0, "Ring of Shooting Stars", "V" },
                    { 119, "Req", "8000gp", "ring", "", 0, "Ring of Spell Storing", "R" },
                    { 120, "Req", "50000gp", "ring", "Rakshasa", 0, "Ring of Spell Turning", "L" },
                    { 121, "", "1800gp", "ring", "", 0, "Ring of Swimming", "U" },
                    { 122, "Req", "25000gp", "ring", "Dreamholder", 0, "Ring of Telekinesis", "V" },
                    { 123, "Req", "5000gp", "ring", "Goat or sheep", 0, "Ring of the Ram", "R" },
                    { 124, "", "150000gp", "ring", "Halfling", 0, "Ring of Three Wishes", "L" },
                    { 125, "Req", "4500gp", "ring", "", 0, "Ring of Warmth", "U" },
                    { 126, "Req", "35000gp", "ring", "Water elemental", 0, "Ring of Water Elemental Command", "L" },
                    { 127, "", "1500gp", "ring", "", 0, "Ring of Water Walking", "U" },
                    { 128, "Req", "6000gp", "ring", "", 0, "Ring of X-ray Vision", "R" },
                    { 129, "", "20gp", "scroll", "", 0, "Cantrip Spell Scroll", "C" },
                    { 130, "", "60gp", "scroll", "", 0, "Ist-level Spell Scroll", "C" },
                    { 131, "", "180gp", "scroll", "", 0, "2nd-level Spell Scroll", "U" },
                    { 132, "", "360gp", "scroll", "", 0, "3rd-level Spell Scroll", "U" },
                    { 133, "", "900gp", "scroll", "", 0, "4th-level Spell Scroll", "R" },
                    { 134, "", "2000gp", "scroll", "", 0, "5th-level Spell Scroll", "R" },
                    { 135, "", "5000gp", "scroll", "", 0, "6th-level Spell Scroll", "V" },
                    { 136, "", "12000gp", "scroll", "", 0, "7th -level Spell Scroll", "V" },
                    { 137, "", "25000gp", "scroll", "", 0, "8th -level Spell Scroll", "V" },
                    { 138, "", "50000gp", "scroll", "", 0, "9th -level Spell Scroll", "L" },
                    { 139, "", "2000gp", "rod", "", 0, "Immovable Rod", "U" },
                    { 140, "Req", "41600gp", "rod", "", 0, "Rod ofAbsorption", "L" },
                    { 141, "Req", "25000gp", "rod", "", 0, "Rod ofAlertness", "V" },
                    { 142, "Req", "35000gp", "rod", "Pit fiend", 0, "Rod of Lordly Might", "L" },
                    { 143, "Req", "6000gp", "rod", "Incubus or sucubus", 0, "Rod of Rulership", "R" },
                    { 144, "", "20000gp", "rod", "Unicorn", 0, "Rod ofSecurity", "v" },
                    { 145, "Req", "1000gp", "rod, staff, or wand", "Fungal heart", 0, "Sporespreader", "U" },
                    { 146, "Req", "4500gp", "rod, staff, or wand", "Fungal heart", 0, "Sporespreader", "R" },
                    { 147, "Req", "900gp", "rod, staff, or wand", "Suneater", 0, "Suncatcher", "U" },
                    { 148, "Req", "2300gp", "rod, staff, or wand", "Suneater", 0, "Suncatcher", "R" },
                    { 149, "Req", "9800gp", "rod, staff, or wand", "Suneater", 0, "Suncatcher", "v" },
                    { 150, "Req", "6000gp", "staff, weapon", "Incubus or sucubus", 0, "Staff of Charming", "R" },
                    { 151, "Req", "12000gp", "staff, weapon", "Magma mephit", 0, "Staff of Fire", "V" },
                    { 152, "Req", "12000gp", "staff, weapon", "Ice mephit", 0, "Staff of Frost", "V" },
                    { 153, "Req", "6000gp", "staff, weapon", "Unicorn", 0, "Staff of Healing", "R" },
                    { 154, "Req", "65000gp", "staff, weapon", "Storm", 0, "Staff of Power", "L" },
                    { 155, "Req", "12000gp", "staff, weapon", "Sprite", 0, "Staff of Striking", "V" },
                    { 156, "Req", "5000gp", "staff, weapon", "Beetle or insect", 0, "Staff of Swarming Insects", "R" },
                    { 157, "Req", "10000gp", "staff, weapon", "Djinni", 0, "Staff of Thunder and Lightning", "V" },
                    { 158, "Req", "2500gp", "staff, weapon", "Wight", 0, "Staff of Withering", "R" },
                    { 159, "Req", "4000000gp", "staff, weapon", "Kraken", 0, "Staff of the Magi", "A" },
                    { 160, "Req", "1200gp", "staff, weapon", "Snake", 0, "Staff of the Python", "U" },
                    { 161, "Req", "22000gp", "staff, weapon", "Dryad", 0, "Staff of the Woodlands", "V" },
                    { 162, "Req", "750gp", "wand", "", 0, "+1 Wand ofthe War Mage", "U" },
                    { 163, "Req", "1500gp", "wand", "", 0, "+2 Wand of the War Mage", "R" },
                    { 164, "Req", "6200gp", "wand", "", 0, "+3 Wand of the War Mage", "V" },
                    { 165, "Req", "5000gp", "wand", "Shambling mound", 0, "Wand of Binding", "R" },
                    { 166, "Req", "1200gp", "wand", "Ankheg", 0, "Wand of Enemy Detection", "U" },
                    { 167, "Req", "5000gp", "wand", "Ghost", 0, "Wand of Fear", "R" },
                    { 168, "Req", "25000gp", "wand", "Fire elemental", 0, "Wand of Fireballs", "V" },
                    { 169, "Req", "25000gp", "wand", "Air elemental", 0, "Wand of Lightning Bolts", "V" },
                    { 170, "Req", "600gp", "wand", "Sphinx", 0, "Wand ofMagic Detection", "U" },
                    { 171, "Req", "900gp", "wand", "", 0, "Wand of Magic Missiles", "U" },
                    { 172, "Req", "10000gp", "wand", "Phase spider", 0, "Wand of Para lysis", "V" },
                    { 173, "Req", "20000gp", "wand", "Mimic", 0, "Wand of Polymorph", "v" },
                    { 174, "Req", "600gp", "wand", "Has blindsight", 0, "Wand of Secrets", "U" },
                    { 175, "Req", "4000gp", "wand", "Spider", 0, "Wand of Web", "R" },
                    { 176, "Req", "4000gp", "wand", "", 0, "Wand of Wonder", "R" },
                    { 177, "", "400gp", "weapon (any axe)", "Fungal heart", 0, "Painblinder Mycaxe", "U" },
                    { 178, "", "1800gp", "weapon (any axe)", "Fungal heart", 0, "Painblinder Mycaxe", "R" },
                    { 179, "Req", "850gp", "weapon (any axe)", "Dreamholder", 0, "Time Splitter", "U" },
                    { 180, "Req", "9800gp", "weapon (any axe)", "Dreamholder", 0, "Time Splitter", "v" },
                    { 181, "Opt", "900gp", "weapon (any bow)", "Suneater", 0, "Sunwing Bow", "U" },
                    { 182, "Opt", "2300gp", "weapon (any bow)", "Suneater", 0, "Sunwing Bow", "R" },
                    { 183, "Opt", "12000gp", "weapon (any bow)", "Suneater", 0, "Sunwing Bow", "V" },
                    { 184, "Opt", "1000gp", "weapon (any hammer*)", "Magnetite", 0, "Haemstrike", "U" },
                    { 185, "Opt", "3500gp", "weapon (any hammer*)", "Magnetite", 0, "Haemstrike", "R" },
                    { 186, "Opt", "11000gp", "weapon (any hammer*)", "Magnetite", 0, "Haemstrike", "V" },
                    { 187, "", "1300gp", "weapon (any hammer*)", "Dreamholder", 0, "Hammer Time", "R" },
                    { 188, "", "6200gp", "weapon (any hammer*)", "Dreamholder", 0, "Hammer Time", "v" },
                    { 189, "Req", "800gp", "weapon (any hammer*)", "Tavern Mimic", 0, "Headbanger Lute", "U" },
                    { 190, "Req", "9600gp", "weapon (any hammer*)", "Tavern Mimic", 0, "Headbanger Lute", "v" },
                    { 191, "Req", "650gp", "weapon (any hammer*)", "Tavern Mimic", 0, "Headbanger Lute", "U" },
                    { 192, "", "1600gp", "weapon (any hammer*)", "Tavern Mimic", 0, "Mawling Maul", "R" },
                    { 193, "", "3200gp", "weapon (any hammer*)", "Tavern Mimic", 0, "Mawling Maul", "R" },
                    { 194, "Opt", "10500gp", "weapon (any two melee)", "Tar-rasque", 0, "Jaw Breakers", "v" },
                    { 195, "", "1400gp", "weapon (any polearm**)", "Mechakobold", 0, "Gunnspier", "R" },
                    { 196, "", "6500gp", "weapon (any polearm**)", "Mechakobold", 0, "Gunnspier", "R" },
                    { 197, "Req", "500gp", "weapon (any sword)", "Treant", 0, "Bonze's Bokken, Wind Ripper", "U" },
                    { 198, "Req", "2100gp", "weapon (any sword)", "Treant", 0, "Bonze's Bokken, Wind Ripper", "R" },
                    { 199, "Req", "9700gp", "weapon (any sword)", "Treant", 0, "Bonze's Bokken, Wind Ripper", "v" },
                    { 200, "Req", "42000gp", "weapon (any sword)", "Treant", 0, "Bonze's Bokken, Wind Ripper", "L" },
                    { 201, "", "1600gp", "weapon (any sword)", "Pygmy rakshasa", 0, "Tail's End", "R" },
                    { 202, "", "6400gp", "weapon (any sword)", "Pygmy rakshasa", 0, "Tail's End", "v" },
                    { 203, "Req", "2600gp", "weapon (any sword)", "Tar-rasque", 0, "Terrorasque", "R" },
                    { 204, "Req", "9900gp", "weapon (any sword)", "Tar-rasque", 0, "Terrorasque", "v" },
                    { 205, "Req", "24000gp", "weapon (any sword)", "", 0, "Vorpal Sword", "L" },
                    { 206, "", "400gp", "weapon (any tommybow)", "Animated", 0, "Splinterspray Tommybow", "U" },
                    { 207, "", "1750gp", "weapon (any tommybow)", "Animated", 0, "Splinterspray Tommybow", "R" },
                    { 208, "", "8100gp", "weapon (any tommybow)", "Animated", 0, "Splinterspray Tommybow", "V" },
                    { 209, "Req", "500gp", "weapon (claw)", "Pygmy rakshasa", 0, "Claws ofCorruption", "U" },
                    { 210, "Req", "9400gp", "weapon (claw)", "Pygmy rakshasa", 0, "Claws ofCorruption", "v" },
                    { 211, "", "1900gp", "weapon (dagger)", "Vrock", 0, "Dagger ofVenom", "R" },
                    { 212, "Req", "600gp", "weapon (flail)", "Polyhedrooze", 0, "Flooze", "U" },
                    { 213, "Req", "9600gp", "weapon (flail)", "Polyhedrooze", 0, "Flooze", "v" },
                    { 214, "", "750gp", "weapon (generic)", "", 0, "+1 weapon", "U" },
                    { 215, "", "1500gp", "weapon (generic)", "", 0, "+2 Weapon", "R" },
                    { 216, "", "6200gp", "weapon (generic)", "", 0, "+3 Weapon", "V" },
                    { 217, "Req", "2100gp", "weapon (generic)", "", 0, "Berserker Axe", "R" },
                    { 218, "Req", "2100gp", "weapon (generic)", "Flying Sword", 0, "Dancing Sword", "RV" },
                    { 219, "Req", "24000gp", "weapon (generic)", "", 0, "Defender", "L" },
                    { 220, "", "2400gp", "weapon (generic)", "", 0, "Dragon Slayer", "R" },
                    { 221, "Req", "9400gp", "weapon (generic)", "", 0, "Flame Tongue", "V" },
                    { 222, "Req", "9400gp", "weapon (generic)", "", 0, "Frost Brand", "v" },
                    { 223, "", "2400gp", "weapon (generic)", "", 0, "Giant Slayer", "R" },
                    { 224, "Req+", "150000gp", "weapon (generic)", "Solar", 0, "Holy Avenger", "L" },
                    { 225, "Req", "170000gp", "weapon (generic)", "", 0, "Luck Blade", "L" },
                    { 226, "Req", "9400gp", "weapon (generic)", "Cat", 0, "Nine Lives Stealer", "v" },
                    { 227, "Req", "2100gp", "weapon (generic)", "Wraith", 0, "Sword of Life Stealing", "R" },
                    { 228, "Req", "2100gp", "weapon (generic)", "", 0, "Sword of Sharpness", "R" },
                    { 229, "Req", "2100gp", "weapon (generic)", "", 0, "Sword of Wounding", "R" },
                    { 230, "", "350gp", "weapon (generic)", "", 0, "Vicious Weapon", "U" },
                    { 231, "Req", "50gp", "weapon (hand crossbow)", "", 0, "Kobold Wristbow", "C" },
                    { 232, "", "1200gp", "weapon (javelin)", "", 0, "Javelin of Lightning", "U" },
                    { 233, "Req", "9400gp", "weapon (longbow)", "", 0, "Oathbow", "V" },
                    { 234, "Req", "12000gp", "weapon (longsword)", "", 0, "Sun Blade", "V" },
                    { 235, "", "1600gp", "weapon (longsword or greatsword)", "Mechakobold", 0, "Pneuma Blade", "R" },
                    { 236, "", "7800gp", "weapon (longsword or greatsword)", "Mechakobold", 0, "Pneuma Blade", "V" },
                    { 237, "Req", "7000gp", "weapon (mace)", "", 0, "Mace of Disruption", "R" },
                    { 238, "", "4500gp", "weapon (mace)", "", 0, "Mace ofSmiting", "R" },
                    { 239, "Req", "7000gp", "weapon (mace)", "", 0, "Mace ofTerror", "R" },
                    { 240, "", "16000gp", "weapon (maul)", "Storm", 0, "Hammer of Thunderbolts", "V" },
                    { 241, "", "850gp", "weapon (rapier)", "Fungal heart", 0, "Longspike", "U" },
                    { 242, "Opt", "10000gp", "weapon (rapier)", "Fungal heart", 0, "Longspike", "V" },
                    { 243, "Req", "9400gp", "weapon (scimitar)", "", 0, "Scimitar ofSpeed", "V" },
                    { 244, "Req", "700gp", "weapon (trident)", "", 0, "Trident of Fish Command", "U" },
                    { 245, "Req", "18000gp", "weapon (warhammer)", "Stone", 0, "Dwarven Thrower", "V" },
                    { 246, "Req", "7000gp", "wondrous item", "Mammoth", 0, "Amulet of Health", "R" },
                    { 247, "Req", "1000gp", "wondrous item", "", 0, "Amu let of Proofagainst Detection and Location", "U" },
                    { 248, "Req", "20000gp", "wondrous item", "", 0, "Amulet of the Planes", "V" },
                    { 249, "", "12000gp", "wondrous item", "", 0, "Apparatus ofthe Crab", "V" },
                    { 250, "", "300gp", "wondrous item", "Dreamholder", 0, "Astral Luggage", "U" },
                    { 251, "", "3200gp", "wondrous item", "Dreamholder", 0, "Astral Luggage", "V" },
                    { 252, "", "2000gp", "wondrous item", "", 0, "Bag of Beans", "R" },
                    { 253, "", "6500gp", "wondrous item", "", 0, "Bag of Devouring", "V" },
                    { 254, "", "2500gp", "wondrous item", "", 0, "Bag of Holding", "U" },
                    { 255, "", "500gp", "wondrous item", "", 0, "Bag of Tricks, (Any)", "U" },
                    { 256, "", "960gp", "wondrous item", "", 0, "Bead of Force", "R" },
                    { 257, "Req", "9500gp", "wondrous item", "", 0, "BeltofDwavvenkind", "V" },
                    { 258, "Req", "24000gp", "wondrous item", "Fire", 0, "Belt of Giant Strength Fire", "V" },
                    { 259, "Req", "16000gp", "wondrous item", "Frost", 0, "Belt of Giant Strength Frost", "V" },
                    { 260, "Req", "8000gp", "wondrous item", "Hill", 0, "Belt of Giant Strength Hill", "R" },
                    { 261, "Req", "16000gp", "wondrous item", "Stone", 0, "Belt of Giant Strength Stone", "V" },
                    { 262, "Req", "96000gp", "wondrous item", "Storm", 0, "Belt of Giant Strength Storm", "L" },
                    { 263, "", "900gp", "wondrous item", "Polyhedrooze", 0, "Bomboozler", "R" },
                    { 264, "", "4800gp", "wondrous item", "Polyhedrooze", 0, "Bomboozler", "V" },
                    { 265, "", "2500gp", "wondrous item", "", 0, "Boots of Elvenkind", "U" },
                    { 266, "Req", "4000gp", "wondrous item", "", 0, "Boots of Levitation", "R" },
                    { 267, "Req", "4000gp", "wondrous item", "", 0, "Boots ofSpeed", "R" },
                    { 268, "Req", "1800gp", "wondrous item", "", 0, "Boots ofStriding and Springing", "U" },
                    { 269, "Req", "2000gp", "wondrous item", "", 0, "Boots of the Winterlands", "U" },
                    { 270, "", "3200gp", "wondrous item", "", 0, "Bowl ofCommanding Water Elementals", "R" },
                    { 271, "Req", "1500gp", "wondrous item", "", 0, "Bracers ofArchery", "R" },
                    { 272, "Req", "6000gp", "wondrous item", "", 0, "Bracers of Defense", "R" },
                    { 273, "", "3200gp", "wondrous item", "Efreeti", 0, "Brazier of Commanding Fire Elementals", "R" },
                    { 274, "Req", "1500gp", "wondrous item", "", 0, "Brooch ofShielding", "U" },
                    { 275, "Req", "3500gp", "wondrous item", "Broodmother", 0, "Broodmother's Embrace", "R" },
                    { 276, "Req", "12000gp", "wondrous item", "Broodmother", 0, "Broodmother's Embrace", "V" },
                    { 277, "Req", "41600gp", "wondrous item", "Broodmother", 0, "Broodmother's Embrace", "L" },
                    { 278, "Req", "800gp", "wondrous item", "Broodmother", 0, "Broodslinger", "U" },
                    { 279, "Req", "2500gp", "wondrous item", "Broodmother", 0, "Broodslinger", "R" },
                    { 280, "Req", "9500gp", "wondrous item", "Broodmother", 0, "Broodslinger", "V" },
                    { 281, "", "8000gp", "wondrous item", "", 0, "Broom of Flying", "V" },
                    { 282, "", "180gp", "wondrous item", "Polyhedrooze", 0, "Caltrooze", "U" },
                    { 283, "Req", "5600gp", "wondrous item", "", 0, "Candle of Invocation", "V" },
                    { 284, "Req", "5600gp", "wondrous item", "", 0, "Candle of Invocation", "v" },
                    { 285, "", "1600gp", "wondrous item", "", 0, "Cape ofthe Mountebank", "R" },
                    { 286, "", "8000gp", "wondrous item", "", 0, "Carpet of Flying, 3 ft. by 5 ft.", "V" },
                    { 287, "", "10000gp", "wondrous item", "", 0, "Carpet of Flying, 4 ft. by 6 ft.", "V" },
                    { 288, "", "12000gp", "wondrous item", "", 0, "Carpet of Flying, 5 ft. by 7 ft.", "V" },
                    { 289, "", "16000gp", "wondrous item", "", 0, "Carpet of Flying, 6 ft. by 9 ft.", "V" },
                    { 290, "", "3200gp", "wondrous item", "Djinni", 0, "Censer of Controlling Air ElementaIs", "R" },
                    { 291, "", "1500gp", "wondrous item", "", 0, "Chime ofOpening", "R" },
                    { 292, "", "360gp", "wondrous item", "", 0, "Circlet of Blasting", "U" },
                    { 293, "Req", "9400gp", "wondrous item", "Giant spider", 0, "Cloak ofArachnida", "V" },
                    { 294, "Req", "60000gp", "wondrous item", "", 0, "Cloak of Displacement", "L" },
                    { 295, "Req", "5000gp", "wondrous item", "", 0, "Cloak of Elvenkind", "R" },
                    { 296, "Req", "3500gp", "wondrous item", "", 0, "Cloak of Protection", "R" },
                    { 297, "Req", "6000gp", "wondrous item", "Bat", 0, "Cloak ofthe Bat", "R" },
                    { 298, "", "5000gp", "wondrous item", "Ray or shark", 0, "Cloak of the Manta Ray", "R" },
                    { 299, "Req", "9400gp", "wondrous item", "Mechakobold and", 0, "Crawly Turrit", "V" },
                    { 300, "Req", "28000gp", "wondrous item", "", 0, "Crystal Ball", "V" },
                    { 301, "Req", "16000gp", "wondrous item", "", 0, "Cube of Force", "V" },
                    { 302, "", "40000gp", "wondrous item", "", 0, "Cubic Gate", "L" },
                    { 303, "", "", "wondrous item", "", 0, "Decanter of Endless Water", "" },
                    { 304, "", "600gp", "wondrous item", "", 0, "Deck of Illusions", "U" },
                    { 305, "", "60000gp", "wondrous item", "", 0, "Deck of Many Things", "L" },
                    { 306, "", "500gp", "wondrous item", "", 0, "Dimensional Doorknob", "U" },
                    { 307, "", "2500gp", "wondrous item", "", 0, "Dimensional Shackles", "R" },
                    { 308, "", "200gp", "wondrous item", "Dreamholder", 0, "Dreamy the Lucid", "U" },
                    { 309, "", "250gp", "wondrous item", "", 0, "Dust of Disappearance", "U" },
                    { 310, "", "180gp", "wondrous item", "", 0, "Dust of Dryness", "U" },
                    { 311, "", "480gp", "wondrous item", "", 0, "Dust of Sneezing and Choking", "U" },
                    { 312, "", "1000gp", "wondrous item", "", 0, "Efficient Quiver", "U" },
                    { 313, "", "30000gp", "wondrous item", "Efreeti", 0, "Efreeti Bottle", "L" },
                    { 314, "", "960gp", "wondrous item", "Djinni", 0, "Elemental Gem, Blue Sapphire", "R" },
                    { 315, "", "960gp", "wondrous item", "", 0, "Elemental Gem, Emerald", "R" },
                    { 316, "", "960gp", "wondrous item", "Efreeti", 0, "Elemental Gem, Red Corundum", "R" },
                    { 317, "", "960gp", "wondrous item", "", 0, "Elemental Gem, Yellow Diamond", "R" },
                    { 318, "", "480gp", "wondrous item", "", 0, "Elemental Gem, Eversmoking Bottle", "U" },
                    { 319, "Req", "1000gp", "wondrous item", "", 0, "Elemental Gem, Eyes ofCharming", "U" },
                    { 320, "", "20gp", "wondrous item", "Mimic", 0, "Elemental Gem, Eyes ofGoogly", "C" },
                    { 321, "", "850gp", "wondrous item", "Bird", 0, "Elemental Gem, Eyes of Minute Seeing", "U" },
                    { 322, "Req", "850gp", "wondrous item", "Eagle", 0, "Elemental Gem, Eyes ofthe Eagle", "U" },
                    { 323, "", "50gp", "wondrous item", "", 0, "Feather Token Anchor", "C" },
                    { 324, "", "3000gp", "wondrous item", "", 0, "Feather Token Bird", "R" },
                    { 325, "", "300gp", "wondrous item", "", 0, "Feather Token Fa n", "U" },
                    { 326, "", "1400gp", "wondrous item", "", 0, "Feather Token Swan Boat", "R" },
                    { 327, "", "50gp", "wondrous item", "", 0, "Feather Token Tree", "C" },
                    { 328, "", "600gp", "wondrous item", "", 0, "Feather Token Whip", "U" },
                    { 329, "Req", "4500gp", "wondrous item", "Pygmy rakshasa", 0, "Feline's Fury", "R" },
                    { 330, "Req", "2100gp", "wondrous item", "Handler", 0, "Felinobelix", "R" },
                    { 331, "Req", "41600gp", "wondrous item", "Handler", 0, "Felinobelix", "L" },
                    { 332, "", "2000gp", "wondrous item", "Griffon", 0, "Figurine of Wondrous Power, Bronze Griffon", "R" },
                    { 333, "", "4000gp", "wondrous item", "Insect", 0, "Figurine of Wondrous Power, Ebony Fly", "R" },
                    { 334, "", "600gp", "wondrous item", "Lion", 0, "Figurine of Wondrous Power, Golden Lions", "U" },
                    { 335, "", "17400gp", "wondrous item", "Goat", 0, "Figurine of Wondrous Power, Ivory Goats", "V" },
                    { 336, "", "6000gp", "wondrous item", "Elephant", 0, "Figurine of Wondrous Power, Marble Elephant", "R" },
                    { 337, "", "24000gp", "wondrous item", "H o rse", 0, "Figurine of Wondrous Power, Obsidian Steed", "V" },
                    { 338, "", "3000gp", "wondrous item", "Dog or wolf", 0, "Figurine of Wondrous Power, Onyx Dog", "R" },
                    { 339, "", "7000gp", "wondrous item", "Owl", 0, "Figurine of Wondrous Power, Serpentine Owl", "R" },
                    { 340, "", "1000gp", "wondrous item", "Bird", 0, "Figurine of Wondrous Power, Silver Raven", "U" },
                    { 341, "", "3000gp", "wondrous item", "", 0, "Folding Boat", "R" },
                    { 342, "Req", "5000gp", "wondrous item", "Ogre", 0, "Gauntlets ofOgre Power", "R" },
                    { 343, "", "5000gp", "wondrous item", "", 0, "Gem of Brightness", "R" },
                    { 344, "Req", "8000gp", "wondrous item", "", 0, "Gem ofSeeing", "R" },
                    { 345, "Req", "1500gp", "wondrous item", "", 0, "Gloves of Missile Snaring", "U" },
                    { 346, "Req", "900gp", "wondrous item", "Shark", 0, "Gloves ofSwimming and Climbing", "U" },
                    { 347, "", "1000gp", "wondrous item", "", 0, "Goggles of Night", "U" },
                    { 348, "", "350gp", "wondrous item", "", 0, "Grill ofBarbecuing", "U" },
                    { 349, "Req", "1200gp", "wondrous item", "Shapechanger", 0, "Hat of Disguise", "U" },
                    { 350, "Req", "5000gp", "wondrous item", "", 0, "Headband of Intellect", "R" },
                    { 351, "", "300gp", "wondrous item", "", 0, "Heliana's Guide to Monster Hunting", "U" },
                    { 352, "Req", "6200gp", "wondrous item", "", 0, "Helm of Brilliance", "V" },
                    { 353, "Req", "25000gp", "wondrous item", "", 0, "Helm of Brilliance", "v" },
                    { 354, "", "500gp", "wondrous item", "", 0, "Helm ofComprehending Languages", "U" },
                    { 355, "Req", "2000gp", "wondrous item", "", 0, "Helm ofTelepathy", "U" },
                    { 356, "Req", "23000gp", "wondrous item", "", 0, "Helm ofTeleportation", "V" },
                    { 357, "", "1500gp", "wondrous item", "", 0, "Handy Haversack", "U" },
                    { 358, "", "450gp", "wondrous item", "", 0, "Horn of Blasting", "U" },
                    { 359, "", "8400gp", "wondrous item", "Elephant", 0, "Horn ofValhalla, Brass", "R" },
                    { 360, "", "14000gp", "wondrous item", "Mammoth", 0, "Horn ofValhalla, Bronze", "V" },
                    { 361, "", "28800gp", "wondrous item", "Balor", 0, "Horn ofValhalla, Iron", "L" },
                    { 362, "", "5600gp", "wondrous item", "Rhinoceros", 0, "Horn ofValhalla, Silver", "R" },
                    { 363, "", "5000gp", "wondrous item", "", 0, "Horseshoes ofSpeed", "R" },
                    { 364, "", "6200gp", "wondrous item", "", 0, "Horseshoes ofa Zephyr", "V" },
                    { 365, "", "500gp", "wondrous item", "Cultist", 0, "Infested Cultist's Skull", "U" },
                    { 366, "", "7000gp", "wondrous item", "", 0, "Instant Fortress", "V" },
                    { 367, "", "75000gp", "wondrous item", "", 0, "Instant Fortress", "L" },
                    { 368, "Req", "9400gp", "wondrous item", "", 0, "loun Stone, Absorption", "v" },
                    { 369, "Req", "9400gp", "wondrous item", "Dex > 20*", 0, "loun Stone, Agility", "V" },
                    { 370, "Req", "12000gp", "wondrous item", "Adult or Ancient", 0, "loun Stone, Awareness", "V" },
                    { 371, "Req", "9400gp", "wondrous item", "Con > 20", 0, "loun Stone, Fortitude", "v" },
                    { 372, "Req", "41600gp", "wondrous item", "Shield guardian", 0, "loun Stone, Greater Absorption", "L" },
                    { 373, "Req", "9400gp", "wondrous item", "Wis > 20", 0, "loun Stone, Insight", "V" },
                    { 374, "Req", "9400gp", "wondrous item", "Int 220*", 0, "loun Stone, Intellect", "V" },
                    { 375, "Req", "9400gp", "wondrous item", "Cha > 20*", 0, "loun Stone, Leadership", "v" },
                    { 376, "Req", "41600gp", "wondrous item", "Pit fiend", 0, "loun Stone, Mastery", "L" },
                    { 377, "Req", "2100gp", "wondrous item", "Gorgon", 0, "loun Stone, Protection", "R" },
                    { 378, "Req", "9400gp", "wondrous item", "Troll", 0, "loun Stone, Regeneration", "V" },
                    { 379, "Req", "5200gp", "wondrous item", "Spellcaster", 0, "loun Stone, Reserve", "R" },
                    { 380, "Req", "9400gp", "wondrous item", "Str > 20*", 0, "loun Stone, Strength", "V" },
                    { 381, "Req", "2100gp", "wondrous item", "Vampire", 0, "loun Stone, Sustenance", "R" },
                    { 382, "", "4000gp", "wondrous item", "Shambling mound", 0, "Iron Bands of Binding", "R" },
                    { 383, "", "28800gp", "wondrous item", "Iron Golem", 0, "Iron Flask", "L" },
                    { 384, "Req", "750gp", "wondrous item", "Mechakobold", 0, "Kobbold Flaymefrower", "U" },
                    { 385, "Req", "9800gp", "wondrous item", "Mechakobold", 0, "Kobbold Flaymefrower", "v" },
                    { 386, "", "900gp", "wondrous item", "Hag", 0, "Lantern of Revealing", "U" },
                    { 387, "", "1500gp", "wondrous item", "", 0, "L'ArsZne's Quadnoculars", "R" },
                    { 388, "Req", "19000gp", "wondrous item", "Rakshasa", 0, "Mantle of Spell Resistance", "V" },
                    { 389, "", "14000gp", "wondrous item", "", 0, "Manual of Bodily Health", "V" },
                    { 390, "", "8200gp", "wondrous item", "Clay golem", 0, "Manual ofClay Golems", "v" },
                    { 391, "", "6200gp", "wondrous item", "Flesh golem", 0, "Manual of Flesh Golems", "v" },
                    { 392, "", "14000gp", "wondrous item", "", 0, "Manual ofGainful Exercise", "v" },
                    { 393, "", "12200gp", "wondrous item", "Iron golem", 0, "Manual of Iron Golems", "v" },
                    { 394, "", "14000gp", "wondrous item", "", 0, "Manual ofQuickness ofAction", "V" },
                    { 395, "", "9200gp", "wondrous item", "Stone golem", 0, "Manual of Stone Golems", "v" },
                    { 396, "", "8600gp", "wondrous item", "", 0, "Marvelous Pigments", "V" },
                    { 397, "Req", "1200gp", "wondrous item", "", 0, "Medallion ofThoughts", "U" },
                    { 398, "", "18000gp", "wondrous item", "", 0, "Mirror of Life Trapping", "V" },
                    { 399, "Req", "2300gp", "wondrous item", "Fungal heart", 0, "Mycelial Cloak", "R" },
                    { 400, "Req", "1200gp", "wondrous item", "", 0, "Necklace ofAdaptation", "U" },
                    { 401, "", "400gp", "wondrous item", "", 0, "Necklace of Fireballs (single bead)", "U" },
                    { 402, "Req", "300gp", "wondrous item", "", 0, "Necklace of Prayer Beads Prayer Bead, Bless", "U" },
                    { 403, "Req", "600gp", "wondrous item", "", 0, "Prayer Bead, Curing", "U" },
                    { 404, "Req", "3200gp", "wondrous item", "", 0, "Prayer Bead, Favor", "R" },
                    { 405, "Req", "600gp", "wondrous item", "", 0, "Prayer Bead, Smiting", "U" },
                    { 406, "Req", "6400gp", "wondrous item", "", 0, "Prayer Bead, Summons", "v" },
                    { 407, "Req", "6400gp", "wondrous item", "", 0, "Prayer Bead, Wind Walk", "V" },
                    { 408, "Req", "3500gp", "wondrous item", "Polyhedrooze", 0, "Oozemat Coat", "R" },
                    { 409, "Req", "4000000gp", "wondrous item", "", 0, "Orb of Dragonkind", "A" },
                    { 410, "Req", "1000gp", "wondrous item", "", 0, "Pearl of Power", "U" },
                    { 411, "", "400gp", "wondrous item", "", 0, "Periapt of Health", "U" },
                    { 412, "", "5000gp", "wondrous item", "", 0, "Periapt of Proofagainst Poison", "R" },
                    { 413, "Req", "800gp", "wondrous item", "", 0, "Periapt of Wound Closure", "U" },
                    { 414, "", "800gp", "wondrous item", "", 0, "Pipes of Haunting", "U" },
                    { 415, "Req", "700gp", "wondrous item", "", 0, "Pipes ofthe Sewers", "U" },
                    { 416, "", "2500gp", "wondrous item", "", 0, "Portable Hole", "R" },
                    { 417, "", "360gp", "wondrous item", "", 0, "Restorative Ointment", "U" },
                    { 418, "Req", "4000gp", "wondrous item", "Sphinx", 0, "Robe of Eyes", "R" },
                    { 419, "Req", "9400gp", "wondrous item", "", 0, "Robe ofScintillating Colors", "v" },
                    { 420, "Req", "18000gp", "wondrous item", "", 0, "Robe ofStars", "V" },
                    { 421, "", "1250gp", "wondrous item", "", 0, "Robe of Useful Items", "U" },
                    { 422, "Req", "41600gp", "wondrous item", "", 0, "Robe ofthe Archmagi", "L" },
                    { 423, "Req", "1600gp", "wondrous item", "Dreamholder", 0, "Robes ofBeauréve", "R" },
                    { 424, "Req", "32000gp", "wondrous item", "Dreamholder", 0, "Robes ofBeauréve", "L" },
                    { 425, "Req", "2100gp", "wondrous item", "Mechakobold", 0, "Rolly Turrit", "R" },
                    { 426, "", "900gp", "wondrous item", "", 0, "Rope of Climbing", "U" },
                    { 427, "", "2000gp", "wondrous item", "", 0, "Rope of Entang lement", "R" },
                    { 428, "Req", "41600gp", "wondrous item", "Lich", 0, "Sca rab of Protection", "L" },
                    { 429, "Req", "2800gp", "wondrous item", "Magnetite", 0, "Shard Crown", "R" },
                    { 430, "Req", "10000gp", "wondrous item", "Magnetite", 0, "Shard Crown", "v" },
                    { 431, "Req", "41600gp", "wondrous item", "Magnetite", 0, "Shard Crown", "L" },
                    { 432, "Req", "700gp", "wondrous item", "Polyhedrooze", 0, "Slime-in-a-Skull", "U" },
                    { 433, "Req", "10000gp", "wondrous item", "Polyhedrooze", 0, "Slime-in-a-Skull", "V" },
                    { 434, "Req", "1500gp", "wondrous item", "Spider", 0, "Slippers ofSpider Climbing", "U" },
                    { 435, "Req", "900gp", "wondrous item", "Wolf", 0, "Snow WolfCowl", "U" },
                    { 436, "Req", "3500gp", "wondrous item", "Wolf", 0, "Snow WolfCowl", "R" },
                    { 437, "Req", "11500gp", "wondrous item", "Wolf", 0, "Snow WolfCowl", "V" },
                    { 438, "", "4800gp", "wondrous item", "Black Pudding", 0, "Sovereign Glue", "V" },
                    { 439, "Req", "850gp", "wondrous item", "Tavern Mimic", 0, "Spelleater Tome", "U" },
                    { 440, "Req", "2700gp", "wondrous item", "Tavern Mimic", 0, "Spelleater Tome", "R" },
                    { 441, "", "15000gp", "wondrous item", "", 0, "Sphere ofAnnihilation", "V" },
                    { 442, "", "3200gp", "wondrous item", "", 0, "Stone ofControlling Earth Elementals", "R" },
                    { 443, "Req", "1500gp", "wondrous item", "Halfling", 0, "Stone ofGood Luck", "U" },
                    { 444, "Req", "500gp", "wondrous item", "Suneater", 0, "SunfeatherShroud", "U" },
                    { 445, "Req", "2100gp", "wondrous item", "Suneater", 0, "SunfeatherShroud", "R" },
                    { 446, "Req", "9400gp", "wondrous item", "Suneater", 0, "SunfeatherShroud", "v" },
                    { 447, "Req", "72000gp", "wondrous item", "Good-aligned god", 0, "Talisman of Pure Good", "L" },
                    { 448, "Req", "62000gp", "wondrous item", "Evil-aligned god", 0, "Talisman of Ultimate Evil", "L" },
                    { 449, "Req", "15000gp", "wondrous item", "", 0, "Talisman ofthe Sphere", "V" },
                    { 450, "Req", "2500gp", "wondrous item", "Tar-rasque", 0, "Tarrobe", "R" },
                    { 451, "Req", "42000gp", "wondrous item", "Tar-rasque", 0, "Tarrobe", "L" },
                    { 452, "", "9200gp", "wondrous item", "", 0, "Tome ofClear Thought", "V" },
                    { 453, "", "9200gp", "wondrous item", "", 0, "Tome of Leadership and Influence", "V" },
                    { 454, "Opt", "750gp", "wondrous item", "Broodmother", 0, "Tome ofLiving Memories", "U" },
                    { 455, "Opt", "2300gp", "wondrous item", "Broodmother", 0, "Tome ofLiving Memories", "R" },
                    { 456, "Opt", "10000gp", "wondrous item", "Broodmother", 0, "Tome ofLiving Memories", "V" },
                    { 457, "", "9200gp", "wondrous item", "", 0, "Tome of Understanding", "V" },
                    { 458, "", "22400gp", "wondrous item", "", 0, "Universal Solvent", "L" },
                    { 459, "Req", "2100gp", "wondrous item", "Polyhedrooze", 0, "Ventilation Unit D-20", "R" },
                    { 460, "Req", "2100gp", "wondrous item", "Tar-rasque", 0, "Viscous Symbiote", "R" },
                    { 461, "Req", "9400gp", "wondrous item", "Tar-rasque", 0, "Viscous Symbiote", "V" },
                    { 462, "Req", "41600gp", "wondrous item", "Tar-rasque", 0, "Viscous Symbiote", "L" },
                    { 463, "", "96000gp", "wondrous item", "", 0, "Well of Many Worlds", "L" },
                    { 464, "", "700gp", "wondrous item", "", 0, "Wind Fan", "U" },
                    { 465, "Req", "6000gp", "wondrous item", "", 0, "Winged Boots", "R" },
                    { 466, "Req", "6000gp", "wondrous item", "", 0, "Wings of Flying", "R" },
                    { 467, "", "3500gp", "wondrous item", "Brass", 0, "Wyrm's Breath Grenade Brass, Sleep", "V" },
                    { 468, "", "1100gp", "wondrous item", "Bronze", 0, "Wyrm's Breath Grenade Bronze, Repulsion", "R" },
                    { 469, "", "1250gp", "wondrous item", "Copper", 0, "Wyrm's Breath Grenade Copper, Slow", "R" },
                    { 470, "", "3200gp", "wondrous item", "Gold", 0, "Wyrm's Breath Grenade Gold, Weakening", "V" },
                    { 471, "", "18000gp", "wondrous item", "Silver", 0, "Wyrm's Breath Grenade Silver, Paralysing", "L" }
                });

            migrationBuilder.InsertData(
                table: "MonsterComponents",
                columns: new[] { "MonsterComponentId", "DC", "Name", "Type" },
                values: new object[,]
                {
                    { 1, "5", "antenna", "Aberration" },
                    { 2, "5", "eye", "Aberration" },
                    { 3, "5", "flesh", "Aberration" },
                    { 4, "5", "phial of blood", "Aberration" },
                    { 5, "10", "bone", "Aberration" },
                    { 6, "10", "egg", "Aberration" },
                    { 7, "10", "fat", "Aberration" },
                    { 8, "10", "pouch of claws", "Aberration" },
                    { 9, "10", "pouch of teeth", "Aberration" },
                    { 10, "10", "tentacle", "Aberration" },
                    { 11, "15", "Heart", "Aberration" },
                    { 12, "15", "phial of mucus", "Aberration" },
                    { 13, "15", "liver", "Aberration" },
                    { 14, "15", "stinger", "Aberration" },
                    { 15, "20", "brain", "Aberration" },
                    { 16, "20", "chitin", "Aberration" },
                    { 17, "20", "hide", "Aberration" },
                    { 18, "20", "main eye", "Aberration" },
                    { 19, "5", "eye", "Celestial" },
                    { 20, "5", "flesh", "Celestial" },
                    { 21, "5", "phial of blood", "Celestial" },
                    { 22, "5", "pouch of dust", "Celestial" },
                    { 23, "10", "bone", "Celestial" },
                    { 24, "10", "fat", "Celestial" },
                    { 25, "10", "horn", "Celestial" },
                    { 26, "10", "pouch of teeth", "Celestial" },
                    { 27, "15", "heart", "Celestial" },
                    { 28, "15", "liver", "Celestial" },
                    { 29, "15", "pouch of feathers", "Celestial" },
                    { 30, "15", "pouch of scales", "Celestial" },
                    { 31, "20", "brain", "Celestial" },
                    { 32, "20", "skin", "Celestial" },
                    { 33, "25", "soul", "Celestial" },
                    { 34, "5", "antenna", "Beast" },
                    { 35, "5", "eye", "Beast" },
                    { 36, "5", "flesh", "Beast" },
                    { 37, "5", "phial of blood", "Beast" },
                    { 38, "10", "antler", "Beast" },
                    { 39, "10", "beak", "Beast" },
                    { 40, "10", "bone", "Beast" },
                    { 41, "10", "egg", "Beast" },
                    { 42, "10", "fat", "Beast" },
                    { 43, "10", "fin", "Beast" },
                    { 44, "10", "horn", "Beast" },
                    { 45, "10", "pincer", "Beast" },
                    { 46, "10", "pouch of claws", "Beast" },
                    { 47, "10", "pouch of teeth", "Beast" },
                    { 48, "10", "talon", "Beast" },
                    { 49, "10", "tusk", "Beast" },
                    { 50, "15", "heart", "Beast" },
                    { 51, "15", "liver", "Beast" },
                    { 52, "15", "poison gland", "Beast" },
                    { 53, "15", "pouch of feathers", "Beast" },
                    { 54, "15", "pouch of scales", "Beast" },
                    { 55, "15", "stinger", "Beast" },
                    { 56, "15", "tentacle", "Beast" },
                    { 57, "20", "chitin", "Beast" },
                    { 58, "20", "pelt", "Beast" },
                    { 59, "5", "phial of blood", "Construct" },
                    { 60, "5", "phial of oil", "Construct" },
                    { 61, "5", "phial of sap", "Construct" },
                    { 62, "10", "flesh", "Construct" },
                    { 63, "10", "plating", "Construct" },
                    { 64, "10", "stone", "Construct" },
                    { 65, "15", "bone", "Construct" },
                    { 66, "15", "heart", "Construct" },
                    { 67, "15", "liver", "Construct" },
                    { 68, "15", "gears", "Construct" },
                    { 69, "20", "brain", "Construct" },
                    { 70, "20", "instructions", "Construct" },
                    { 71, "25", "lifespark", "Construct" },
                    { 72, "5", "eye", "Dragon" },
                    { 73, "5", "flesh", "Dragon" },
                    { 74, "5", "phial of blood", "Dragon" },
                    { 75, "10", "bone", "Dragon" },
                    { 76, "10", "egg", "Dragon" },
                    { 77, "10", "fat", "Dragon" },
                    { 78, "10", "pouch of claws", "Dragon" },
                    { 79, "10", "pouch of teeth", "Dragon" },
                    { 80, "15", "horn", "Dragon" },
                    { 81, "15", "liver", "Dragon" },
                    { 82, "15", "pouch of scales", "Dragon" },
                    { 83, "20", "heart", "Dragon" },
                    { 84, "25", "breath sac", "Dragon" },
                    { 85, "5", "eye", "Elemental" },
                    { 86, "5", "primordial dust", "Elemental" },
                    { 87, "10", "bone", "Elemental" },
                    { 88, "15", "volatile mote of air/earth/fire/water", "Elemental" },
                    { 89, "25", "core of air/earth/fire/water", "Elemental" },
                    { 90, "5", "antenna", "Fey" },
                    { 91, "5", "eye", "Fey" },
                    { 92, "5", "flesh", "Fey" },
                    { 93, "5", "phial of blood", "Fey" },
                    { 94, "10", "antler", "Fey" },
                    { 95, "10", "beak", "Fey" },
                    { 96, "10", "bone", "Fey" },
                    { 97, "10", "egg", "Fey" },
                    { 98, "10", "horn", "Fey" },
                    { 99, "10", "pouch of claws", "Fey" },
                    { 100, "10", "pouch of teeth", "Fey" },
                    { 101, "10", "talon", "Fey" },
                    { 102, "10", "tusk", "Fey" },
                    { 103, "15", "heart", "Fey" },
                    { 104, "15", "fat", "Fey" },
                    { 105, "15", "liver", "Fey" },
                    { 106, "15", "poison gland", "Fey" },
                    { 107, "15", "pouch of feathers", "Fey" },
                    { 108, "15", "pouch of scales", "Fey" },
                    { 109, "15", "tentacle", "Fey" },
                    { 110, "15", "tongue", "Fey" },
                    { 111, "20", "brain", "Fey" },
                    { 112, "20", "skin", "Fey" },
                    { 113, "20", "pelt", "Fey" },
                    { 114, "25", "psyche", "Fey" },
                    { 115, "5", "eye", "Fiend" },
                    { 116, "5", "flesh", "Fiend" },
                    { 117, "5", "phial of blood", "Fiend" },
                    { 118, "5", "pouch of dust", "Fiend" },
                    { 119, "10", "bone", "Fiend" },
                    { 120, "10", "horn", "Fiend" },
                    { 121, "10", "pouch of claws", "Fiend" },
                    { 122, "10", "pouch of teeth", "Fiend" },
                    { 123, "15", "heart", "Fiend" },
                    { 124, "15", "fat", "Fiend" },
                    { 125, "15", "liver", "Fiend" },
                    { 126, "15", "poison gland", "Fiend" },
                    { 127, "15", "pouch of feathers", "Fiend" },
                    { 128, "15", "pouch of scales", "Fiend" },
                    { 129, "20", "brain", "Fiend" },
                    { 130, "20", "skin", "Fiend" },
                    { 131, "25", "soul", "Fiend" },
                    { 132, "5", "flesh", "Giant" },
                    { 133, "5", "nail", "Giant" },
                    { 134, "5", "phial of blood", "Giant" },
                    { 135, "10", "bone", "Giant" },
                    { 136, "10", "fat", "Giant" },
                    { 137, "10", "tooth", "Giant" },
                    { 138, "15", "heart", "Giant" },
                    { 139, "15", "liver", "Giant" },
                    { 140, "20", "skin", "Giant" },
                    { 141, "5", "eye", "Humanoid" },
                    { 142, "5", "phial of blood", "Humanoid" },
                    { 143, "5", "bone", "Humanoid" },
                    { 144, "10", "egg", "Humanoid" },
                    { 145, "10", "pouch of teeth", "Humanoid" },
                    { 146, "15", "heart", "Humanoid" },
                    { 147, "15", "liver", "Humanoid" },
                    { 148, "15", "pouch of feathers", "Humanoid" },
                    { 149, "15", "pouch of scales", "Humanoid" },
                    { 150, "20", "brain", "Humanoid" },
                    { 151, "20", "skin", "Humanoid" },
                    { 152, "5", "antenna", "Monstrosity" },
                    { 153, "5", "eye", "Monstrosity" },
                    { 154, "5", "flesh", "Monstrosity" },
                    { 155, "5", "phial of blood", "Monstrosity" },
                    { 156, "10", "antler", "Monstrosity" },
                    { 157, "10", "beak", "Monstrosity" },
                    { 158, "10", "bone", "Monstrosity" },
                    { 159, "10", "egg", "Monstrosity" },
                    { 160, "10", "fat", "Monstrosity" },
                    { 161, "10", "fin", "Monstrosity" },
                    { 162, "10", "horn", "Monstrosity" },
                    { 163, "10", "pincer", "Monstrosity" },
                    { 164, "10", "pouch of claws", "Monstrosity" },
                    { 165, "10", "pouch of teeth", "Monstrosity" },
                    { 166, "10", "talon", "Monstrosity" },
                    { 167, "10", "tusk", "Monstrosity" },
                    { 168, "15", "heart", "Monstrosity" },
                    { 169, "15", "liver", "Monstrosity" },
                    { 170, "15", "poison gland", "Monstrosity" },
                    { 171, "15", "pouch of feathers", "Monstrosity" },
                    { 172, "15", "pouch of scales", "Monstrosity" },
                    { 173, "15", "stinger", "Monstrosity" },
                    { 174, "15", "tentacle", "Monstrosity" },
                    { 175, "20", "chitin", "Monstrosity" },
                    { 176, "20", "pelt", "Monstrosity" },
                    { 177, "5", "phial of acid", "Ooze" },
                    { 178, "10", "phial of mucus", "Ooze" },
                    { 179, "15", "vesicle", "Ooze" },
                    { 180, "20", "membrane", "Ooze" },
                    { 181, "??", "random components p101", "Ooze" },
                    { 182, "5", "phial of sap", "Plant" },
                    { 183, "5", "tuber", "Plant" },
                    { 184, "10", "bundle of roots", "Plant" },
                    { 185, "10", "phial of wax", "Plant" },
                    { 186, "10", "pouch of hyphae", "Plant" },
                    { 187, "10", "pouch of leaves", "Plant" },
                    { 188, "15", "poison gland", "Plant" },
                    { 189, "15", "pouch of pollen", "Plant" },
                    { 190, "15", "pouch of spores", "Plant" },
                    { 191, "20", "bark", "Plant" },
                    { 192, "20", "membrane", "Plant" },
                    { 193, "5", "eye", "Undead" },
                    { 194, "5", "bone", "Undead" },
                    { 195, "5", "phial of congealed blood", "Undead" },
                    { 196, "10", "marrow", "Undead" },
                    { 197, "10", "pouch of teeth", "Undead" },
                    { 198, "10", "rancid fat", "Undead" },
                    { 199, "15", "ethereal ichor", "Undead" },
                    { 200, "15", "undying flesh", "Undead" },
                    { 201, "20", "undying heart", "Undead" }
                });

            migrationBuilder.InsertData(
                table: "Tools",
                columns: new[] { "ToolId", "AbilityRequirement", "ItemTypes", "Name" },
                values: new object[,]
                {
                    { 1, "Dexterity", "Armour (light or hide), weapons (whips)", "Leatherworker" },
                    { 2, "Intelligence", "Potions; miscellaneous (any salves or lotions)", "Alchemist" },
                    { 3, "Constitution", "Potions", "Brewer" },
                    { 4, "Dexterity", "Scrolls", "Calligrapher" },
                    { 5, "Dexterity", "Ammunition (arrows and bolts), rods, staves, wands, weapons (polearms, blowguns, clubs, darts, greatclubs, javelins, longbows, nunchucks, quarterstaves, shortbows, tridents); miscellaneous (anything made of wood)", "Carpenter" },
                    { 6, "Dexterity", "Miscellaneous (footwear)", "Cobbler" },
                    { 7, "Dexterity", "Maps; miscellaneous (anything involving paper)", "Cartographer" },
                    { 8, "Constitution", "Food", "Cook utensils" },
                    { 9, "Constitution", "Rods, staves, wands; miscellaneous (anything made of glass)", "Glassblower" },
                    { 10, "Intelligence", "Potions; miscellaneous (any salves or lotions)", "Herbalism kit" },
                    { 11, "Dexterity", "Miscellaneous (anything involving jewels or precious metals)", "Jeweller" },
                    { 12, "Strength", "Miscellaneous (anything made of stone)", "Mason" },
                    { 13, "Dexterity", "Scrolls", "Painter" },
                    { 14, "Dexterity", "Poisons", "Poisoner" },
                    { 15, "Dexterity", "Miscellaneous (anything made of clay)", "Potter" },
                    { 16, "Strength", "Armour (heavy or medium except hide), rods, staves, wands, weapons (axes, polearms, swords, daggers, flails, javelins, light hammers, maces, mauls, morningstars, tridents, war picks)", "Smith" },
                    { 17, "Dexterity", "Rods, staves, wands, weapons (crossbows, firearms, tommybows), wondrous items (anything with a mechanism)", "Tinker" },
                    { 18, "Constitution", "Armour (padded), weapons (nets, slings); miscellaneous (cloaks, hats, robes, anything made of cloth)", "Weaver" },
                    { 19, "Dexterity", "Ammunition (arrows and bolts), rods, staves, wands, weapons (polearms, blowguns, clubs, darts, greatclubs, javelins, longbows, nunchucks, quarterstaves, shortbows, tridents); miscellaneous (anything made of wood)", "Woodcarver" }
                });

            migrationBuilder.InsertData(
                table: "Weapons",
                columns: new[] { "WeaponId", "DC", "Damage", "ItemValue", "MaterialCost", "Name", "Properties", "TimeToCraft", "ToolId", "WeaponType", "Weight" },
                values: new object[,]
                {
                    { 1, "14", "1d6 slashing", "5gp", "2gp", "Claw", "Light, special", 3.0, 16, "Simple Melee Weapon", "2lb" },
                    { 2, "14", "1d4 bludgeoning", "1sp", "3cp", "Club", "Light", 0.25, 5, "Simple Melee Weapon", "2lb" },
                    { 3, "14", "1d4 piercing", "2gp", "7sp", "Dagger", "Finesse, light, thrown (range 20/60)", 1.0, 16, "Simple Melee Weapon", "1lb" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Armors");

            migrationBuilder.DropTable(
                name: "Essence");

            migrationBuilder.DropTable(
                name: "MagicItems");

            migrationBuilder.DropTable(
                name: "MonsterComponents");

            migrationBuilder.DropTable(
                name: "Tools");

            migrationBuilder.DropTable(
                name: "Weapons");
        }
    }
}
